DROP TABLE IF EXISTS points CASCADE;

CREATE TABLE points (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    function_id BIGINT REFERENCES functions(id),
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    index INT NOT NULL
);